"""make wcag_ref nullable

Revision ID: 6b33c84f1acb
Revises: 57c40c5b406f
Create Date: 2026-09-28 08:25:48.994977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b33c84f1acb'
down_revision: Union[str, Sequence[str], None] = '57c40c5b406f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accessibility_issues', 'wcag_ref',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accessibility_issues', 'wcag_ref',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
